// Writes src/routes.gen.ts: one import per src/routes/**/route.ts, with the
// URL it answers (folder names like [id] and [...path] are parameters, the
// same convention the routes followed in the Next.js app).
// Runs before `dev` and `build`; the output is committed so type checks work.
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve("src/routes");
const files = readdirSync(root, { recursive: true })
  .map((file) => String(file).split(path.sep).join("/"))
  .filter((file) => file.endsWith("/route.ts"))
  .sort();

const lines = [
  "// Generated by scripts/generate-routes.mjs from src/routes/**/route.ts. Don't edit by hand.",
  'import type { RouteModule } from "./http/router";',
  "",
];
const entries = [];
files.forEach((file, i) => {
  const pattern = `/${file.replace(/\/route\.ts$/, "")}`;
  lines.push(`import * as route${i} from "./routes/${file.replace(/\.ts$/, "")}";`);
  entries.push(`  { pattern: ${JSON.stringify(pattern)}, module: route${i} as unknown as RouteModule },`);
});
lines.push("", "export const routeTable = [", ...entries, "];", "");

writeFileSync("src/routes.gen.ts", lines.join("\n"));
console.log(`[routes] ${files.length} routes`);
