// Generated by scripts/generate-routes.mjs from src/routes/**/route.ts. Don't edit by hand.
import type { RouteModule } from "./http/router";

import * as route0 from "./routes/api/admin/activity/route";
import * as route1 from "./routes/api/admin/analytics/overview/route";
import * as route2 from "./routes/api/admin/analytics/realtime/route";
import * as route3 from "./routes/api/admin/applications/[id]/cv/route";
import * as route4 from "./routes/api/admin/applications/[id]/route";
import * as route5 from "./routes/api/admin/applications/route";
import * as route6 from "./routes/api/admin/applications/stats/route";
import * as route7 from "./routes/api/admin/auth/login/route";
import * as route8 from "./routes/api/admin/auth/logout/route";
import * as route9 from "./routes/api/admin/auth/me/route";
import * as route10 from "./routes/api/admin/auth/password/route";
import * as route11 from "./routes/api/admin/auth/refresh/route";
import * as route12 from "./routes/api/admin/clients/[id]/[action]/route";
import * as route13 from "./routes/api/admin/clients/[id]/route";
import * as route14 from "./routes/api/admin/clients/route";
import * as route15 from "./routes/api/admin/enquiries/[id]/route";
import * as route16 from "./routes/api/admin/enquiries/route";
import * as route17 from "./routes/api/admin/enquiries/stats/route";
import * as route18 from "./routes/api/admin/insights/[id]/[action]/route";
import * as route19 from "./routes/api/admin/insights/[id]/route";
import * as route20 from "./routes/api/admin/insights/route";
import * as route21 from "./routes/api/admin/jobs/[id]/[action]/route";
import * as route22 from "./routes/api/admin/jobs/[id]/route";
import * as route23 from "./routes/api/admin/jobs/route";
import * as route24 from "./routes/api/admin/offices/[id]/[action]/route";
import * as route25 from "./routes/api/admin/offices/[id]/route";
import * as route26 from "./routes/api/admin/offices/route";
import * as route27 from "./routes/api/admin/overview/route";
import * as route28 from "./routes/api/admin/pages/[page]/[action]/route";
import * as route29 from "./routes/api/admin/pages/[page]/route";
import * as route30 from "./routes/api/admin/partners/[id]/[action]/route";
import * as route31 from "./routes/api/admin/partners/[id]/route";
import * as route32 from "./routes/api/admin/partners/route";
import * as route33 from "./routes/api/admin/projects/[id]/[action]/route";
import * as route34 from "./routes/api/admin/projects/[id]/route";
import * as route35 from "./routes/api/admin/projects/route";
import * as route36 from "./routes/api/admin/services/[id]/[action]/route";
import * as route37 from "./routes/api/admin/services/[id]/route";
import * as route38 from "./routes/api/admin/services/route";
import * as route39 from "./routes/api/admin/settings/[group]/route";
import * as route40 from "./routes/api/admin/solutions/[id]/[action]/route";
import * as route41 from "./routes/api/admin/solutions/[id]/route";
import * as route42 from "./routes/api/admin/solutions/route";
import * as route43 from "./routes/api/admin/uploads/route";
import * as route44 from "./routes/api/admin/users/[id]/route";
import * as route45 from "./routes/api/admin/users/route";
import * as route46 from "./routes/api/v1/applications/route";
import * as route47 from "./routes/api/v1/enquiries/route";
import * as route48 from "./routes/api/v1/insights/[slug]/route";
import * as route49 from "./routes/api/v1/pages/[page]/route";
import * as route50 from "./routes/api/v1/services/[slug]/route";
import * as route51 from "./routes/api/v1/slugs/[kind]/route";
import * as route52 from "./routes/api/v1/solutions/[slug]/route";
import * as route53 from "./routes/api/v1/work/[slug]/route";

export const routeTable = [
  { pattern: "/api/admin/activity", module: route0 as unknown as RouteModule },
  { pattern: "/api/admin/analytics/overview", module: route1 as unknown as RouteModule },
  { pattern: "/api/admin/analytics/realtime", module: route2 as unknown as RouteModule },
  { pattern: "/api/admin/applications/[id]/cv", module: route3 as unknown as RouteModule },
  { pattern: "/api/admin/applications/[id]", module: route4 as unknown as RouteModule },
  { pattern: "/api/admin/applications", module: route5 as unknown as RouteModule },
  { pattern: "/api/admin/applications/stats", module: route6 as unknown as RouteModule },
  { pattern: "/api/admin/auth/login", module: route7 as unknown as RouteModule },
  { pattern: "/api/admin/auth/logout", module: route8 as unknown as RouteModule },
  { pattern: "/api/admin/auth/me", module: route9 as unknown as RouteModule },
  { pattern: "/api/admin/auth/password", module: route10 as unknown as RouteModule },
  { pattern: "/api/admin/auth/refresh", module: route11 as unknown as RouteModule },
  { pattern: "/api/admin/clients/[id]/[action]", module: route12 as unknown as RouteModule },
  { pattern: "/api/admin/clients/[id]", module: route13 as unknown as RouteModule },
  { pattern: "/api/admin/clients", module: route14 as unknown as RouteModule },
  { pattern: "/api/admin/enquiries/[id]", module: route15 as unknown as RouteModule },
  { pattern: "/api/admin/enquiries", module: route16 as unknown as RouteModule },
  { pattern: "/api/admin/enquiries/stats", module: route17 as unknown as RouteModule },
  { pattern: "/api/admin/insights/[id]/[action]", module: route18 as unknown as RouteModule },
  { pattern: "/api/admin/insights/[id]", module: route19 as unknown as RouteModule },
  { pattern: "/api/admin/insights", module: route20 as unknown as RouteModule },
  { pattern: "/api/admin/jobs/[id]/[action]", module: route21 as unknown as RouteModule },
  { pattern: "/api/admin/jobs/[id]", module: route22 as unknown as RouteModule },
  { pattern: "/api/admin/jobs", module: route23 as unknown as RouteModule },
  { pattern: "/api/admin/offices/[id]/[action]", module: route24 as unknown as RouteModule },
  { pattern: "/api/admin/offices/[id]", module: route25 as unknown as RouteModule },
  { pattern: "/api/admin/offices", module: route26 as unknown as RouteModule },
  { pattern: "/api/admin/overview", module: route27 as unknown as RouteModule },
  { pattern: "/api/admin/pages/[page]/[action]", module: route28 as unknown as RouteModule },
  { pattern: "/api/admin/pages/[page]", module: route29 as unknown as RouteModule },
  { pattern: "/api/admin/partners/[id]/[action]", module: route30 as unknown as RouteModule },
  { pattern: "/api/admin/partners/[id]", module: route31 as unknown as RouteModule },
  { pattern: "/api/admin/partners", module: route32 as unknown as RouteModule },
  { pattern: "/api/admin/projects/[id]/[action]", module: route33 as unknown as RouteModule },
  { pattern: "/api/admin/projects/[id]", module: route34 as unknown as RouteModule },
  { pattern: "/api/admin/projects", module: route35 as unknown as RouteModule },
  { pattern: "/api/admin/services/[id]/[action]", module: route36 as unknown as RouteModule },
  { pattern: "/api/admin/services/[id]", module: route37 as unknown as RouteModule },
  { pattern: "/api/admin/services", module: route38 as unknown as RouteModule },
  { pattern: "/api/admin/settings/[group]", module: route39 as unknown as RouteModule },
  { pattern: "/api/admin/solutions/[id]/[action]", module: route40 as unknown as RouteModule },
  { pattern: "/api/admin/solutions/[id]", module: route41 as unknown as RouteModule },
  { pattern: "/api/admin/solutions", module: route42 as unknown as RouteModule },
  { pattern: "/api/admin/uploads", module: route43 as unknown as RouteModule },
  { pattern: "/api/admin/users/[id]", module: route44 as unknown as RouteModule },
  { pattern: "/api/admin/users", module: route45 as unknown as RouteModule },
  { pattern: "/api/v1/applications", module: route46 as unknown as RouteModule },
  { pattern: "/api/v1/enquiries", module: route47 as unknown as RouteModule },
  { pattern: "/api/v1/insights/[slug]", module: route48 as unknown as RouteModule },
  { pattern: "/api/v1/pages/[page]", module: route49 as unknown as RouteModule },
  { pattern: "/api/v1/services/[slug]", module: route50 as unknown as RouteModule },
  { pattern: "/api/v1/slugs/[kind]", module: route51 as unknown as RouteModule },
  { pattern: "/api/v1/solutions/[slug]", module: route52 as unknown as RouteModule },
  { pattern: "/api/v1/work/[slug]", module: route53 as unknown as RouteModule },
];
